const array=[
    {   
        id:"01.",
        question:"When was NASA's mars rover 'Curiosity' launched?",
        answer:"August 6,2012",
        hint:"It was between 2011 - 2013 in the month of August",
        message:"Please answer in the following format e.g. May 19,2017",
    },{ 
        id:"02.",
        question:"What is the name of the technique used in AI where machines learn from experience without being explicitly programmed?",
        answer:"Machine Learning",
        hint:"It comes together with Artificial Intelligence(AI) and start with M",
        message:"",
    },{
        id:"03.",
        question:"Which country became the first to ban deforestation in 2017?",
        answer:"Norway",
        hint:"It's a country in Europe",
        message:"",
    },{
        id:"04.",
        question:"Who proposed the hierarchy of needs theory?",
        answer:"Abraham Maslow",
        hint:"Born in 1908, he was an alumni of University of Wisconsin",
        message:"",
    },{ 
        id:"05.",
        question:" Which animal has the longest lifespan of any mammal?",
        answer:"Bowhead whale",
        hint:"It is a marine animal that can live over 200 years",
        message:"Specify the species name e.g. Siberian Tiger (not Just Tiger)",
    },{
        id:"06.",
        question:"Which space agency successfully landed the first rover on the far side of the moon?",
        answer:"China National Space Administration",
        hint:"It is a Chinese space agency",
        message:"Answer with full name e.g. National Aeronautics and Space Administration",
    },{
        id:"07.",
        question:"In which country did the Impressionist art movement originate?",
        answer:"France",
        hint:"Impressionism painting was founded by French painter Claude Monet.",
        message:"",
    },{ 
        id:"08.",
        question:" Which desert is the largest hot desert in the world? ",
        answer:"The Sahara Desert",
        hint:"It is located in North Africa",
        message:"Answer using 'The' infront of the name e.g. The Nile River",
    },{
        id:"09.",
        question:"What is the most abundant gas in the Earth’s atmosphere?",
        answer:"Nitrogen",
        hint:"It make up about 78% of gas in atmospheric air",
        message:"",
    },{
        id:"10.",
        question:"What is the term for a market structure in which a single company dominates the market?",
        answer:"Monoploy",
        hint:"The term refers to a market structure that consists of a single seller or producer and no close substitutes.",
        message:"",
    },{
        id:"11.",
        question:"Which famous artist painted 'The Starry Night'?",
        answer:"Vincent van Gogh",
        hint:"He was a Dutch painter who also painted 'Wheatfield with Crows'",
        message:"Answer with his full name",
    },{
        id:"12.",
        question:"In which country were the first modern Olympic Games held?",
        answer:"Greece",
        hint:"It was first held in the year 1896",
        message:"",
    },{
        id:"13.",
        question:"Which bird is known for its distinctive “laughing” call and is native to Australia?",
        answer:"Kookaburra",
        hint:" Though they belong to the larger group known as 'kingfishers', they are not closely associated with water.",
        message:"",
    },{
        id:"14.",
        question:"What is the term for a psychological condition where someone experiences persistent feelings of sadness?",
        answer:"Depression",
        hint:"It affects about 3.5% of the global population, or about 280 million people of all ages (as of 2020).",
        message:"",
    },{
        id:"15.",
        question:"Which material is commonly used in aerospace engineering due to its strength and lightweight properties?",
        answer:"Titanium",
        hint:"Its name comes from the name of the strong Greek gods called Titans and was discovered in 1791 by William Gregor.",
        message:"Please answer with its symbol e.g. Oxygen(O)",
    },{
        id:"16.",
        question:"What is the speed of light in vacuum (in meters per second)?",
        answer:"299,792,458 m/s",
        hint:"It is more than 200 hundred millions meters per second",
        message:"Answer should be like e.g.211,343,456 m/s",
    },{
        id:"17.",
        question:"Which country is the largest producer of coffee in the world?",
        answer:"Brazil",
        hint:"It is also a country with the most water resources",
        message:"",
    },{
        id:"18.",
        question:"Which animal has the highest blood pressure in the animal kingdom?",
        answer:"Giraffe",
        hint:"They are also known for their incredibly long neck.",
        message:"",
    },{
        id:"19.",
        question:"What is the name of the engineering discipline that deals with the design of aircraft and spacecraft?",
        answer:"Aerospace engineering",
        hint:"It has two major and overlapping branches: aeronautical engineering and astronautical engineering.",
        message:"Include 'engineering' at the end of the answer e.g. Marine Engineering",
    },{
        id:"20.",
        question:"What is the name of the telescope launched in 1990 that has provided some of the most detailed images of space?",
        answer:"Hubble Space Telescope",
        hint:"The Telescope is named after astronomer Edwin Hubble and is one of NASA's Great Observatories.",
        message:"",
    },{
        id:"21.",
        question:"What is the term for a warship that is designed to protect other ships in a convoy?",
        answer:"Destroyer",
        hint:"They were originally conceived in 1885 by Fernando Villaamil for the Spanish Navy as a defense against torpedo boats",
        message:"",
    },{
        id:"22.",
        question:"What does ISO stand for in photography?",
        answer:"International Standards Organization",
        hint:"It is related to the sensitivity of the camera's sensor.",
        message:"",
    },{
        id:"23.",
        question:"What is the name of the software commonly used for editing and manipulating digital images?",
        answer:"Adobe Photoshop",
        hint:"It's developer is Adobe company.",
        message:"",
    },{
        id:"24.",
        question:"Which country’s navy is the largest in the world by the number of ships?",
        answer:"China",
        hint:"It's a country in Asia with one of the largest population in the world",
        message:"",
    },{
        id:"25.",
        question:"What type of aircraft engine is primarily used in commercial jetliners?",
        answer:"Turbofan engine",
        hint:"They are the most efficient engines in the range of speeds from about 500 to 1,000 km/h (270 to 540 kn; 310 to 620 mph), the speed at which most commercial aircraft operate.",
        message:"Add engine at the end of the answer e.g. Propeller engine",
    }
];